idea:
    build: .
    labels:
        org.kurron.description: "JetBrains 0xDBE SQL IDE"
        org.kurron.version: "preview"
    container_name: "0xDBE"
    net: "host"
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/vagrant:/home/developer
    environment:
        DISPLAY: unix:0.0
    user: 1000:1000
